### Eye Calibration ROS Logger Configuration ###

[logger]

# General parameters
timer_period = 0.1
target_nodes = ["eye_calibration"]

# Console logger parameters
"console.n_log" = 5
"console.n_flush" = 5
"console.filter" = ["PE"]
"console.config.precision" = 3
"console.config.separator" = "  "
"console.config.sign" = "+"

# CSV logger parameters
"csv.n_log" = 1
"csv.n_flush" = 100
"csv.filter" = ["PE"]

# WandB logger parameters
"wandb.n_log" = 1
"wandb.n_flush" = 40
"wandb.filter" = ["PE"]
"wandb.config.entity" = "u1999168-girona"
"wandb.config.project" = "visual_control|eyecalib"
"wandb.config.params" = [
    "eye_calibration-ref.pose",
    "eye_calibration-ref.pose.tol",
    "eye_calibration-sam.variant",
    "eye_calibration-sam.prompt.n_pos",
    "eye_calibration-sam.prompt.n_neg",
    "eye_calibration-pose.n_view_sqrt",
    "eye_calibration-pose.dist",
    "eye_calibration-pose.range.elev",
    "eye_calibration-pose.range.azim",
    "eye_calibration-dr.mesh.scale",
    "eye_calibration-dr.mesh.elev_lim",
    "eye_calibration-dr.mesh.azim_lim",
    "eye_calibration-dr.model.type",
    "eye_calibration-dr.model.res",
    "eye_calibration-dr.model.scale",
    "eye_calibration-dr.model.n_level",
    "eye_calibration-dr.model.log2_hsz",
    "eye_calibration-dr.model.mlp_n_layer",
    "eye_calibration-dr.shader.sigma",
    "eye_calibration-dr.shader.boxlen",
    "eye_calibration-dr.shader.knum",
    "eye_calibration-dr.raster.size",
    "eye_calibration-dr.raster.backend",
    "eye_calibration-dr.optim.loss",
    "eye_calibration-dr.optim.loss.weights",
    "eye_calibration-dr.optim.loss.symmetry",
    "eye_calibration-dr.optim.loss.tan_norm",
    "eye_calibration-dr.optim.lr",
    "eye_calibration-dr.optim.sched.T_0",
    "eye_calibration-dr.optim.sched.T_mult",
    "eye_calibration-dr.optim.sched.eta_min",
    "eye_calibration-dr.optim.n_iter.init",
    "eye_calibration-dr.optim.n_iter.text",
    "eye_calibration-dr.optim.n_iter.full",
]
