### PBVS ROS Logger Configuration ###

[logger]

# General parameters
timer_period = 0.1
target_nodes = ["apriltag_detector", "apriltag_estimator", "pbvs_controller"]

# Console logger parameters
"console.n_log" = 5
"console.n_flush" = 5
"console.filter" = ["JT", "PE"]
"console.config.precision" = 3
"console.config.separator" = "  "
"console.config.sign" = "+"

# CSV logger parameters
"csv.n_log" = 1
"csv.n_flush" = 100
"csv.filter" = [""]

# WandB logger parameters
"wandb.n_log" = 1
"wandb.n_flush" = 40
"wandb.filter" = ["JS", "JT", "PE"]
"wandb.config.entity" = "u1999168-girona"
"wandb.config.project" = "visual_control|VS"
"wandb.config.params" = [
    "apriltag_detector-size",
    "apriltag_detector-tile_size",
    "apriltag_detector-backends",
    "apriltag_estimator-tag.P_tthr",
    "apriltag_estimator-tag.P_rthr",
    "apriltag_estimator-ekf.P0_diag",
    "apriltag_estimator-ekf.Q_diag",
    "apriltag_estimator-ekf.R_diag",
    "pbvs_controller-tag.tag_ids",
    "pbvs_controller-ik.eps",
    "pbvs_controller-ik.lambda",
    "pbvs_controller-robot.max_tvel",
    "pbvs_controller-robot.max_rvel",
    "pbvs_controller-robot.max_vel_sf",
    "pbvs_controller-robot.max_qdot",
    "pbvs_controller-ctrl.conv_ttol",
    "pbvs_controller-ctrl.conv_rtol",
    "pbvs_controller-ctrl.lambda",
]
