### Eye Detector Configuration ###

[detector]

# Reference pose parameters
"ref.dist" = 0.4
"ref.tol" = [3e-3, 5e-3]

# SAM2 parameters
"sam.variant" = "sam2.1-hiera-small"
"sam.prompt.n_pos" = 3

# Mesh parameters
"dr.mesh.scale" = 1.0
"dr.mesh.elev_lim" = [-25.0, 20.0]
"dr.mesh.azim_lim" = [-90.0, 90.0]

# Model parameters
"dr.model.n_rep" = 1
"dr.model.pos" = [0.005, 0.005, 0.01]
"dr.model.tan" = [0.05, 0.05]
"dr.model.scale" = 0.05

# Shader parameters
"dr.shader.sigma" = 3e-5
"dr.shader.boxlen" = 1e-2
"dr.shader.knum" = 10

# Rasterization parameters
"dr.raster.size" = 256

# Optimizer parameters
"dr.optim.loss" = ["l1_loss", "l1_loss"]
"dr.optim.loss.weights" = [0.5, 0.5]
"dr.optim.loss.tan_norm" = 1e-5
"dr.optim.lr" = 2e-2
"dr.optim.sched.eta_min" = 3e-4
"dr.optim.n_iter.init" = 200
"dr.optim.n_iter" = 20


# Backend-type and number of iteration specific overrides
[overrides-cuda-10]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyedtc_sweeps/sweeps/uqw960ex/runs/ytwdhp9w?nw=nwuseru1999168
"dr.shader.sigma" = 5.518e-5
"dr.shader.boxlen" = 1.492e-3
"dr.optim.lr" = 1.684e-2
"dr.optim.sched.eta_min" = 1.240e-4
"dr.optim.loss" = ["l1_loss", "l1_loss"]


[overrides-cuda-20]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyedtc_sweeps/sweeps/hefpjxxh/runs/ebqv1czf?nw=nwuseru1999168
"dr.shader.sigma" = 2.396e-5
"dr.shader.boxlen" = 2.388e-4
"dr.optim.lr" = 1.634e-2
"dr.optim.sched.eta_min" = 2.261e-5
"dr.optim.loss" = ["l1_loss", "l1_loss"]


[overrides-nvdiffrast-10]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyedtc_sweeps/sweeps/uqw960ex/runs/ytwdhp9w?nw=nwuseru1999168
"dr.shader.sigma" = 5.518e-5
"dr.shader.boxlen" = 1.492e-3
"dr.optim.lr" = 1.684e-2
"dr.optim.sched.eta_min" = 1.240e-4
"dr.optim.loss" = ["l1_loss", "l1_loss"]


[overrides-nvdiffrast-20]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyedtc_sweeps/sweeps/z6kzi0sx/runs/vjc5tcqm?nw=nwuseru1999168
"dr.shader.sigma" = 2.396e-5
"dr.shader.boxlen" = 2.388e-4
"dr.optim.lr" = 1.634e-2
"dr.optim.sched.eta_min" = 2.261e-5
"dr.optim.loss" = ["l1_loss", "l1_loss"]
