### Apriltag Estimator Configuration ###

[estimator]

# AprilTag parameters
"tag.timeout" = 0.5
"tag.P_tthr" = 0.1
"tag.P_rthr" = 0.1
"tag.ema_alpha" = 0.02

# EKF parameters
"ekf.P0_diag" = [
    6.250e-4,  # 0.025m**2
    6.250e-4,  # 0.025m**2
    2.500e-3,  # 0.05m**2
    6.400e-3,  # 0.08rad**2
    6.400e-3,  # 0.08rad**2
    2.250e-2,  # 0.15rad**2
]
"ekf.Q_diag" = [
    4.600e-4,  # 0.02m**2
    4.600e-4,  # 0.02m**2
    4.600e-4,  # 0.02m**2
    1.000e-4,  # 0.01rad**2
    1.000e-4,  # 0.01rad**2
    1.000e-4,  # 0.01rad**2
]
"ekf.R_diag" = [
    6.250e-4,  # 0.025m**2
    6.250e-4,  # 0.025m**2
    2.500e-3,  # 0.05m**2
    6.400e-3,  # 0.08rad**2
    6.400e-3,  # 0.08rad**2
    2.250e-2,  # 0.15rad**2
]