### Apriltag Estimator Configuration ###

[estimator]  # https://wandb.ai/u1999168-girona/visual_control%7CVS_sweeps/runs/9hboxrjg?nw=nwuseru1999168

# AprilTag parameters
"tag.timeout" = 0.5
"tag.P_tthr" = 0.1
"tag.P_rthr" = 0.1
"tag.ema_alpha" = 0.02

# EKF parameters
"ekf.P0_diag" = [
    6.250e-4,  # 0.025m**2
    6.250e-4,  # 0.025m**2
    2.500e-3,  # 0.05m**2
    2.250e-2,  # 0.15rad**2
    2.250e-2,  # 0.15rad**2
    6.400e-3,  # 0.08rad**2
]
"ekf.Q_diag" = [
    7.730e-6,
    7.730e-6,
    2.708e-6,
    1.446e-6,
    1.446e-6,
    1.557e-5,
]
"ekf.R_diag" = [
    6.250e-4,  # 0.025m**2
    6.250e-4,  # 0.025m**2
    2.500e-3,  # 0.05m**2
    2.250e-2,  # 0.15rad**2
    2.250e-2,  # 0.15rad**2
    6.400e-3,  # 0.08rad**2
]