### Apriltag Estimator Configuration for ChArUco Boards ###

[estimator]  # https://wandb.ai/u1999168-girona/visual_control%7Checalib_sweeps/runs/dyol81kg?nw=nwuseru1999168

# AprilTag parameters
"tag.timeout" = 0.5
"tag.P_tthr" = 0.1
"tag.P_rthr" = 0.1
"tag.ema_alpha" = 0.02

# EKF parameters
"ekf.P0_diag" = [
    6.250e-4,  # 0.025m**2
    6.250e-4,  # 0.025m**2
    2.500e-3,  # 0.05m**2
    2.250e-2,  # 0.15rad**2
    2.250e-2,  # 0.15rad**2
    6.400e-3,  # 0.08rad**2
]
"ekf.Q_diag" = [
    1.080e-6,
    1.080e-6,
    6.424e-6,
    1.083e-6,
    1.083e-6,
    1.119e-6,
]
"ekf.R_diag" = [
    6.250e-4,  # 0.025m**2
    6.250e-4,  # 0.025m**2
    2.500e-3,  # 0.05m**2
    2.250e-2,  # 0.15rad**2
    2.250e-2,  # 0.15rad**2
    6.400e-3,  # 0.08rad**2
]