### Apriltag Estimator Configuration for ChArUco Boards ###

[estimator]  # https://wandb.ai/u1999168-girona/visual_control%7Checalib_sweeps/sweeps/d8ywfeey/runs/phsackzd

# AprilTag parameters
"tag.timeout" = 0.5
"tag.P_tthr" = 0.1
"tag.P_rthr" = 0.1
"tag.ema_alpha" = 0.02

# EKF parameters
"ekf.P0_diag" = [
    6.250e-4,  # 0.025m**2
    6.250e-4,  # 0.025m**2
    2.500e-3,  # 0.05m**2
    2.250e-2,  # 0.15rad**2
    2.250e-2,  # 0.15rad**2
    6.400e-3,  # 0.08rad**2
]
"ekf.Q_diag" = [
    6.149e-4,
    6.149e-4,
    2.800e-4,
    5.716e-6,
    5.716e-6,
    9.205e-4,
]
"ekf.R_diag" = [
    6.250e-4,  # 0.025m**2
    6.250e-4,  # 0.025m**2
    2.500e-3,  # 0.05m**2
    2.250e-2,  # 0.15rad**2
    2.250e-2,  # 0.15rad**2
    6.400e-3,  # 0.08rad**2
]