### IBVS ROS Sweep Configuration ###

# Launch script parameters  
[launch]

# General parameters
timer_period = 0.1
n_runs_per_set = 3
target_nodes = ["apriltag_detector", "apriltag_estimator", "ibvs_controller"]

# Objective function parameters
"obj.flags" = [
    "jnt_vel",
    "jnt_delta_vel",
    "pos",
    "rot",
    "pose",
]
"obj.weights" = [
    0.02,
    0.1,
    0.0,
    0.0,
    1.0,
]

# WandB logger parameters
"wandb.n_log" = 1
"wandb.n_flush" = 40
"wandb.config.entity" = "u1999168-girona"
"wandb.config.project" = "visual_control|VS_sweeps"
"wandb.config.params" = [
    "apriltag_detector-size",
    "apriltag_detector-tile_size",
    "apriltag_detector-backends",
    "apriltag_estimator-tag.P_tthr",
    "apriltag_estimator-tag.P_rthr",
    "apriltag_estimator-ekf.P0_diag",
    "apriltag_estimator-ekf.R_diag",
    "ibvs_controller-tag.tag_ids",
    "ibvs_controller-ik.lambda",
    "ibvs_controller-robot.max_tvel",
    "ibvs_controller-robot.max_rvel",
    "ibvs_controller-robot.max_vel_sf",
    "ibvs_controller-robot.max_qdot",
    "ibvs_controller-ctrl.lambda",
]


# Sweep hyperparameters
[sweep]
program = "scripts/sweepers/ros_sweeper.py"
method = "bayes"

[sweep.metric]
name = "objective"
goal = "minimize"

[sweep.parameters]
"apriltag_estimator-ekf.Q_diag.idx_01" = { distribution = "log_uniform_values", min = 1e-6, max = 1e-3 }
"apriltag_estimator-ekf.Q_diag.idx_2" = { distribution = "log_uniform_values", min = 1e-6, max = 1e-3 }
"apriltag_estimator-ekf.Q_diag.idx_34" = { distribution = "log_uniform_values", min = 1e-6, max = 1e-3 }
"apriltag_estimator-ekf.Q_diag.idx_5" = { distribution = "log_uniform_values", min = 1e-6, max = 1e-3 }

"ibvs_controller-ik.eps" = { distribution = "log_uniform_values", min = 1e-4, max = 0.1 }
"ibvs_controller-ctrl.lpf_coeff" = { min = 0.1, max = 1.0 }
"ibvs_controller-ctrl.conv_ttol" = { distribution = "log_uniform_values", min = 1e-4, max = 2.5e-3 }
