### OC Planner Configuration ###

[planner]

# General parameters
n_pub = 100
n_update = 100

# Dynamic model parameters
"model.alpha" = 1e-3
"model.fp" = [0.0, 0.0, 0.0]

# Cost function parameters
"cost.Q_x_diag" = [
    100.0, 100.0, 100.0,  # px, py, pz
    100.0, 100.0, 100.0,  # rx, ry, ry
    50.0, 50.0, 50.0,  # vx, vy, vz
    50.0, 50.0, 50.0,  # wx, wy, wz
]
"cost.R_u_diag" = [
    90.0, 90.0, 90.0,  # vdotx, vdoty, vdotz
    90.0, 90.0, 90.0,  # wdotx, wdoty, wdotz
]

# Constraint parameters
"constraint.lh" = [-1.0, -1.0, -1.0, -1.0, -0.41, -0.3]
"constraint.uh" = [9e-4, 2.5e-3, 4.5e-4, 1.25e-3, 0.41, 0.3]
# "constraint.uh" = [2.25e-4, 2.5e-3, 4.5e-4, 1.25e-3, 0.41, 0.3]

# Solver parameters
"solver.n_horizon" = 100
"solver.time_step" = 0.15
"solver.nlp_solver_max_iter" = 100
"solver.nlp_tol" = 1e-5
"solver.qp_solver_iter_max" = 50
"solver.qp_tol" = 1e-5


# Overrides
[overrides-fast]
n_pub = 80
n_update = 80
"solver.n_horizon" = 80
"solver.time_step" = 0.1
"constraint.uh" = [2.5e-3, 2.5e-3, 2.5e-3, 2.5e-3, 0.41, 0.3]
