### OC Planner Configuration ###

[planner]

# General parameters
n_update = 20

# Dynamic model parameters
"model.alpha" = 1e-3
"model.fp" = [0.0, 0.0, 0.0]

# Cost function parameters
"cost.Q_x_diag" = [
    350.0, # px
    350.0, # py
    350.0, # pz
    50.0,  # rx
    50.0,  # ry
    50.0,  # rz
    10.0,  # vx
    10.0,  # vy
    10.0,  # vz
    10.0,  # wx
    10.0,  # wy
    10.0,  # wz
]
"cost.R_u_diag" = [
    1.0, # vdotx
    1.0, # vdoty
    1.0, # vdotz
    1.0, # wdotx
    1.0, # wdoty
    1.0, # wdotz
]
"cost.Q_z_diag" = [
    1.0, # sdot_x
    1.0, # sdot_y
]

# Constraint parameters
"constraint.lbx" = [-0.4, -0.4, -0.4, -0.4, -0.4, -0.4]
"constraint.ubx" = [0.4, 0.4, 0.4, 0.4, 0.4, 0.4]
"constraint.idxbx" = [7, 8, 9, 10, 11, 12]
"constraint.lbu" = [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0]
"constraint.ubu" = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
"constraint.idxbu" = [0, 1, 2, 3, 4, 5]
"constraint.lh" = [-300.0, -220.0]
"constraint.uh" = [300.0, 220.0]

# Solver parameters
"solver.n_horizon" = 60
"solver.time_step" = 0.1
"solver.nlp_solver_max_iter" = 100
"solver.nlp_tol" = 1e-5
"solver.qp_solver_iter_max" = 50
"solver.qp_tol" = 1e-5
