### PBVS Controller Configuration ###

# Tuned values derived from ideal simulation environment
[controller]  # https://wandb.ai/u1999168-girona/visual_control|VS_sweeps/runs/rmrkz865?nw=nwuseru1999168

# General parameters
timeout = 0.5

# IK solver parameters
"ik.eps" = 8.732e-2
"ik.lambda" = 1e-2
"ik.max_iters" = 50
"ik.weight_js" = [
  1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
]  # diag(1.0, 1.0, 1.0, 1.0, 1.0, 1.0)

# Robot parameters
"robot.max_tvel" = 0.5
"robot.max_rvel" = 0.5
"robot.max_vel_sf" = 1.0
"robot.max_qdot" = [
    2.094395102,  # 120 DPS
    2.094395102,  # 120 DPS
    3.141592654,  # 180 DPS
    3.141592654,  # 180 DPS
    3.141592654,  # 180 DPS
    3.141592654,  # 180 DPS
]

# Controller parameters
"ctrl.lpf_coeff" = 0.680
"ctrl.conv_ttol" = 1.462e-3
"ctrl.conv_rtol" = 4.880e-4
"ctrl.lambda" = [
  1.0,
  1.0,
  1.0,
  0.75,
  0.75,
  0.75,
]
