### Eye Calibration Configuration ###

[calibration]

# Reference pose parameters
"ref.pose.tol" = [0.005, 0.025]

# SAM2 parameters
"sam.variant" = "sam2.1-hiera-small"
"sam.prompt.n_pos" = 4
"sam.prompt.n_neg" = 8

# Target pose parameters
"pose.n_view_sqrt" = 3
"pose.prop_cut" = 0.0
"pose.range.dist" = [0.25, 0.3]
"pose.range.elev" = [15.0, -10.0] 
"pose.range.azim" = [5.0, -5.0]

# Mesh parameters
"dr.mesh.scale" = 1.0
"dr.mesh.elev_lim" = [-25.0, 20.0]
"dr.mesh.azim_lim" = [-90.0, 90.0]

# Model parameters
"dr.model.res" = 512
"dr.model.scale" = 0.05
"dr.model.mesh_scale" = 0.25
"dr.model.n_level" = 5
"dr.model.log2_hsz" = 14
"dr.model.mlp_n_layer" = 1

# Shader parameters
"dr.shader.sigma" = 3e-5
"dr.shader.boxlen" = 1e-2
"dr.shader.knum" = 10

# Rasterization parameters
"dr.raster.size" = 256

# Optimizer parameters
"dr.optim.loss" = ["l1_loss", "l1_loss"]
"dr.optim.loss.weights" = [0.5, 0.5]
"dr.optim.loss.symmetry" = 5e-2
"dr.optim.loss.tan_norm" = 5e-4
"dr.optim.loss.laplacian" = 1e-2
"dr.optim.lr" = 2e-2
"dr.optim.sched.T_0" = 300
"dr.optim.sched.T_mult" = 1
"dr.optim.sched.eta_min" = 1e-4
"dr.optim.n_iter.init" = 50
"dr.optim.n_iter.text" = 20
"dr.optim.n_iter.full" = 600


# Model-type and backend specific overrides
[overrides-simple-cuda]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/g6qt0foh?nw=nwuseru1999168
"dr.shader.sigma" = 1.418e-5
"dr.shader.boxlen" = 3.196e-4
"dr.optim.loss.symmetry" = 3.491e-3
"dr.optim.loss.laplacian" = 1.312e-4
"dr.optim.lr" = 4.364e-2
"dr.optim.sched.eta_min" = 4.792e-5
"dr.optim.loss" = ["l1_loss", "l1_loss"]


[overrides-simple-nvdiffrast]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/qk4dmvtd?nw=nwuseru1999168
"dr.shader.sigma" = 3.389e-5
"dr.shader.boxlen" = 1.297e-4
"dr.optim.loss.symmetry" = 2.251e-3
"dr.optim.loss.laplacian" = 5.126e-5
"dr.optim.lr" = 1.864e-2
"dr.optim.sched.eta_min" = 9.288e-6
"dr.optim.loss" = ["mse_loss", "mse_loss"]


[overrides-mipmap-cuda]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/kg6zifgr?nw=nwuseru1999168
"dr.shader.sigma" = 3.769e-5
"dr.shader.boxlen" = 4.582e-4
"dr.optim.loss.symmetry" = 2.843e-3
"dr.optim.loss.laplacian" = 1.432e-5
"dr.optim.lr" = 3.470e-2
"dr.optim.sched.eta_min" = 6.060e-5
"dr.optim.loss" = ["l1_loss", "l1_loss"]


[overrides-mipmap-nvdiffrast]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/ej4tyail?nw=nwuseru1999168
"dr.shader.sigma" = 1.572e-5
"dr.shader.boxlen" = 1.076e-4
"dr.optim.loss.symmetry" = 8.600e-3
"dr.optim.loss.laplacian" = 1.026e-4
"dr.optim.lr" = 3.282e-2
"dr.optim.sched.eta_min" = 3.311e-5
"dr.optim.loss" = ["mse_loss", "mse_loss"]


[overrides-hashenc-cuda]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/0czcjtxa?nw=nwuseru1999168
"dr.model.n_level" = 16
"dr.shader.sigma" = 3.129e-5
"dr.shader.boxlen" = 1.099e-4
"dr.optim.loss.symmetry" = 2.346e-3
"dr.optim.loss.laplacian" = 3.354e-4
"dr.optim.lr" = 4.957e-2
"dr.optim.sched.eta_min" = 9.543e-6
"dr.optim.loss" = ["mse_loss", "mse_loss"]


[overrides-hashenc-nvdiffrast]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/ul2ohc4z?nw=nwuseru1999168
"dr.model.n_level" = 16
"dr.shader.sigma" = 9.918e-5
"dr.shader.boxlen" = 1.287e-4
"dr.optim.loss.symmetry" = 6.896e-3
"dr.optim.loss.laplacian" = 1.123e-4
"dr.optim.lr" = 3.784e-2
"dr.optim.sched.eta_min" = 2.119e-5
"dr.optim.loss" = ["l1_loss", "l1_loss"]
