### Eye Calibration Configuration ###

[calibration]

# Reference pose parameters
"ref.pose.tol" = [0.005, 0.025]

# SAM2 parameters
"sam.variant" = "sam2.1-hiera-small"
"sam.prompt.n_pos" = 3
"sam.prompt.n_neg" = 8

# Target pose parameters
"pose.n_view_sqrt" = 3
"pose.prop_cut" = 0.25
"pose.range.dist" = [0.25, 0.3]
"pose.range.elev" = [15.0, -10.0] 
"pose.range.azim" = [5.0, -5.0]

# Mesh parameters
"dr.mesh.scale" = 1.0
"dr.mesh.elev_lim" = [-25.0, 20.0]
"dr.mesh.azim_lim" = [-90.0, 90.0]

# Model parameters
"dr.model.res" = 512
"dr.model.scale" = 0.05
"dr.model.mesh_scale" = 0.5
"dr.model.n_level" = 5
"dr.model.log2_hsz" = 14
"dr.model.mlp_n_layer" = 1

# Shader parameters
"dr.shader.sigma" = 3e-5
"dr.shader.boxlen" = 1e-2
"dr.shader.knum" = 10

# Rasterization parameters
"dr.raster.size" = 256

# Optimizer parameters
"dr.optim.loss" = ["l1_loss", "l1_loss"]
"dr.optim.loss.weights" = [0.5, 0.5]
"dr.optim.loss.symmetry" = 5e-2
"dr.optim.loss.tan_norm" = 5e-4
"dr.optim.loss.laplacian" = 1e-2
"dr.optim.lr" = 2e-2
"dr.optim.sched.T_0" = 150
"dr.optim.sched.T_mult" = 1
"dr.optim.sched.eta_min" = 1e-4
"dr.optim.n_iter.init" = 50
"dr.optim.n_iter.text" = 20
"dr.optim.n_iter.full" = 300


# Model-type and backend specific overrides
[overrides-simple-cuda]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/xbh2rhcv?nw=nwuseru1999168
"dr.shader.sigma" = 9.827e-6
"dr.shader.boxlen" = 4.844e-4
"dr.optim.loss.symmetry" = 1.839e-3
"dr.optim.loss.laplacian" = 3.048e-5
"dr.optim.lr" = 5.042e-3
"dr.optim.sched.eta_min" = 1.054e-5
"dr.optim.loss" = ["mse_loss", "mse_loss"]


[overrides-simple-nvdiffrast]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/qk4dmvtd?nw=nwuseru1999168
"dr.shader.sigma" = 3.389e-5
"dr.shader.boxlen" = 1.297e-4
"dr.optim.loss.symmetry" = 2.251e-3
"dr.optim.loss.laplacian" = 5.126e-5
"dr.optim.lr" = 1.864e-2
"dr.optim.sched.eta_min" = 9.288e-6
"dr.optim.loss" = ["mse_loss", "mse_loss"]


[overrides-mipmap-cuda]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/3ylaugif?nw=nwuseru1999168
"dr.shader.sigma" = 5.742e-5
"dr.shader.boxlen" = 1.798e-3
"dr.optim.loss.symmetry" = 6.961e-4
"dr.optim.loss.laplacian" = 1.208e-5
"dr.optim.lr" = 3.751e-2
"dr.optim.sched.eta_min" = 7.926e-5
"dr.optim.loss" = ["mse_loss", "mse_loss"]


[overrides-mipmap-nvdiffrast]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/pyljj9gc?nw=nwuseru1999168
"dr.shader.sigma" = 8.256e-5
"dr.shader.boxlen" = 3.235e-4
"dr.optim.loss.symmetry" = 1.911e-3
"dr.optim.loss.laplacian" = 4.307e-4
"dr.optim.lr" = 3.275e-2
"dr.optim.sched.eta_min" = 2.355e-5
"dr.optim.loss" = ["mse_loss", "mse_loss"]


[overrides-hashenc-cuda]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/vagm5auf?nw=nwuseru1999168
"dr.model.n_level" = 16
"dr.shader.sigma" = 8.605e-5
"dr.shader.boxlen" = 2.854e-4
"dr.optim.loss.symmetry" = 4.474e-3
"dr.optim.loss.laplacian" = 5.537e-5
"dr.optim.lr" = 3.308e-2
"dr.optim.sched.eta_min" = 4.488e-5
"dr.optim.loss" = ["mse_loss", "mse_loss"]


[overrides-hashenc-nvdiffrast]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/d2ueglz6?nw=nwuseru1999168
"dr.model.n_level" = 16
"dr.shader.sigma" = 9.440e-5
"dr.shader.boxlen" = 5.056e-4
"dr.optim.loss.symmetry" = 3.583e-3
"dr.optim.loss.laplacian" = 1.340e-5
"dr.optim.lr" = 2.874e-2
"dr.optim.sched.eta_min" = 2.222e-5
"dr.optim.loss" = ["mse_loss", "mse_loss"]
