### Eye Calibration Configuration ###

[calibration]

# Reference pose parameters
"ref.pose.tol" = [0.005, 0.025]

# SAM2 parameters
"sam.variant" = "sam2.1-hiera-small"
"sam.prompt.n_pos" = 3
"sam.prompt.n_neg" = 2

# Target pose parameters
"pose.n_view_sqrt" = 3
"pose.dist" = 0.3
"pose.range.elev" = [15.0, -10.0] 
"pose.range.azim" = [2.5, -10.0]

# Mesh parameters
"dr.mesh.scale" = 1.0
"dr.mesh.elev_lim" = [-30.0, 25.0]
"dr.mesh.azim_lim" = [-90.0, 90.0]

# Model parameters
"dr.model.res" = 512
"dr.model.scale" = 0.05
"dr.model.n_level" = 5
"dr.model.log2_hsz" = 14
"dr.model.mlp_n_layer" = 0

# Shader parameters
"dr.shader.sigma" = 3e-5
"dr.shader.boxlen" = 1e-2
"dr.shader.knum" = 10

# Rasterization parameters
"dr.raster.size" = 256

# Optimizer parameters
"dr.optim.loss" = ["l1_loss", "l1_loss"]
"dr.optim.loss.weights" = [0.5, 0.5]
"dr.optim.loss.symmetry" = 5e-2
"dr.optim.loss.tan_norm" = 5e-4
"dr.optim.lr" = 2e-2
"dr.optim.sched.T_0" = 150
"dr.optim.sched.T_mult" = 1
"dr.optim.sched.eta_min" = 3e-4
"dr.optim.n_iter.init" = 100
"dr.optim.n_iter.text" = 20
"dr.optim.n_iter.full" = 300


# Model-type and backend specific overrides
[overrides-simple-cuda]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/4h69kxzn?nw=nwuseru1999168
"dr.model.res" = 256
"dr.shader.sigma" = 1.289e-6
"dr.shader.boxlen" = 2.074e-2
"dr.optim.loss.tan_norm" = 9.635e-4
"dr.optim.loss.symmetry" = 6.413e-3
"dr.optim.lr" = 5.254e-2
"dr.optim.sched.eta_min" = 1.807e-5
"dr.optim.loss" = ["mse_loss", "mse_loss"]


[overrides-simple-nvdiffrast]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/dat5m4nh?nw=nwuseru1999168
"dr.model.res" = 256
"dr.shader.sigma" = 1.367e-6
"dr.shader.boxlen" = 3.723e-2
"dr.optim.loss.tan_norm" = 6.094e-4
"dr.optim.loss.symmetry" = 3.571e-2
"dr.optim.lr" = 2.087e-2
"dr.optim.sched.eta_min" = 4.175e-5
"dr.optim.loss" = ["mse_loss", "mse_loss"]


[overrides-mipmap-cuda]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/ij1j119d?nw=nwuseru1999168
"dr.model.res" = 512
"dr.shader.sigma" = 1.043e-6
"dr.shader.boxlen" = 1.827e-2
"dr.optim.loss.tan_norm" = 9.789e-4
"dr.optim.loss.symmetry" = 8.635e-2
"dr.optim.lr" = 4.454e-2
"dr.optim.sched.eta_min" = 2.704e-6
"dr.optim.loss" = ["dice_loss", "mncc_loss"]


[overrides-mipmap-nvdiffrast]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/o1tqs196?nw=nwuseru1999168
"dr.model.res" = 512
"dr.shader.sigma" = 3.997e-5
"dr.shader.boxlen" = 2.503e-2
"dr.optim.loss.tan_norm" = 5.013e-4
"dr.optim.loss.symmetry" = 3.674e-2
"dr.optim.lr" = 6.689e-2
"dr.optim.sched.eta_min" = 4.500e-6
"dr.optim.loss" = ["mse_loss", "mse_loss"]


[overrides-hashenc-cuda]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/08pteigl?nw=nwuseru1999168
"dr.model.res" = 1024
"dr.model.n_level" = 16
"dr.shader.sigma" = 6.694e-6
"dr.shader.boxlen" = 6.595e-3
"dr.optim.loss.tan_norm" = 9.479e-4
"dr.optim.loss.symmetry" = 1.287e-2
"dr.optim.lr" = 1.000e-2
"dr.optim.sched.eta_min" = 5.742e-5
"dr.optim.loss" = ["dice_loss", "mncc_loss"]


[overrides-hashenc-nvdiffrast]  # https://wandb.ai/u1999168-girona/visual_control%7Ceyecalib_sweeps/runs/cn4wci1i?nw=nwuseru1999168
"dr.model.res" = 1024
"dr.model.n_level" = 16
"dr.shader.sigma" = 1.895e-5
"dr.shader.boxlen" = 3.807e-2
"dr.optim.loss.tan_norm" = 6.519e-4
"dr.optim.loss.symmetry" = 1.512e-2
"dr.optim.lr" = 1.882e-2
"dr.optim.sched.eta_min" = 1.731e-6
"dr.optim.loss" = ["dice_loss", "mncc_loss"]