### HandEye Calibration Configuration ###

[calibration]

# Convergence tolerance parameters
"calib.conv_ttol" = 0.03
"calib.conv_rtol" = 0.1

# Calibration engine parameters
"calib.eng.n_poses" = 3
"calib.eng.rot_angle" = 0.3
"calib.eng.dist_to_target" = 0.5
"calib.eng.calib_method" = "CALIB_HAND_EYE_TSAI"
