### TCP Calibration (PyTorch3D) Configuration ###

[calibration]

# SAM2 parameters
"sam.variant" = "sam2.1-hiera-tiny"
"sam.prompt.type" = "points"
"sam.prompt.n_pos" = 3
"sam.prompt.n_neg" = 4

# Mesh parameters
"dr.mesh.radius" = 0.003
"dr.mesh.height" = 0.025
"dr.mesh.resolution" = 20
"dr.mesh.split" = 4

# Pose initialization parameters
"dr.init.dist" = 0.125
"dr.init.elev" = 135.0
"dr.init.azim" = 0.0

# Model parameters
"dr.model.radius" = false
"dr.model.height" = true
"dr.model.scale" = 0.1

# Shader parameters
"dr.shader.sigma" = 1e-5
"dr.shader.gamma" = 1e-4
"dr.shader.zfar" = 1.0

# Rasterization parameters
"dr.raster.size" = 256
"dr.raster.n_faces" = 10

# Optimizer parameters
"dr.optim.n_rep" = 8
"dr.optim.sigma" = [0.005, 0.1]
"dr.optim.loss" = ["mse_loss", "mse_loss"]
"dr.optim.loss.weights" = [1.0, 1.0]
"dr.optim.lr.min" = 5e-3
"dr.optim.lr.max" = 0.1
"dr.optim.sched" = true
"dr.optim.sched.eta_min" = 3e-4
"dr.optim.n_iter" = 100